# Copyright 2020 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_antlr4_library(
  name = 'hello',
  module = 'pants_antlr4.test.eval',
  sources = ['Hello.g4'],
)
