[package]
version = "0.0.1"
name = "bazel_protos"
authors = [ "Pants Build <pantsbuild@gmail.com>" ]

[dependencies]
futures = "0.1.16"
grpcio = { git = "https://github.com/pingcap/grpc-rs", rev = "648a299392112a4e173178592a7b6f1eda87e5a3" }
protobuf = "1.4.1"
